name: Bug
description: Zgłoś błąd
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: Co się stało?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Jak odtworzyć?
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Przeglądarka / urządzenie
