import json,os,urllib.request
H={'Authorization':'Bearer '+os.environ['GH_TOKEN'],'Accept':'application/vnd.github+json','Content-Type':'application/json'}
FOOT="\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\nhttps://claude.ai/code/session_01GS2ZCY3HVphcSditk6mGNU"
CFOOT="\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
def req(m,u,d=None):
    r=urllib.request.Request('https://api.github.com/repos/woogitsu/kuking.pl'+u,method=m,headers=H,data=json.dumps(d).encode() if d is not None else None)
    try: return json.load(urllib.request.urlopen(r))
    except urllib.error.HTTPError as e: print('ERR',e.code,e.read()[:300]); raise
