"""Wzorce oczekiwanej przyczyny kontroli negatywnych Alfa 0.8 (#1011).

Klucz to nazwa kontroli z `checks` w `scripts/kontrole-negatywne-alfa08.py`
(literówka wywraca preflight z nazwą kontroli). Wartość to wyrażenie regularne
(`re.search`, `re.DOTALL`) dopasowywane do komunikatu KAŻDEJ porażki po mutacji,
z białymi znakami zwiniętymi do jednej spacji. Jedna kontrola może mieć kilka
porażek (szeroki filtr, testy z data providerem) — wtedy wzorzec jest alternatywą
`a|b`, a KAŻDA porażka musi pasować do którejś jej gałęzi.

JAK PISAĆ WZORZEC. Wskaż regułę, którą mutacja ma naruszyć: fragment WŁASNEGO
komunikatu asercji (`assertTrue($x, 'Bramka pomija job …')`) albo tekst, którego
brakuje w wyniku (`contains "1 aktywnych ukryć"`). Nie wystarczy ogólne
`Failed asserting that` — pasuje do każdej cudzej asercji, czyli do niczego.
Nie wpisuj ścieżek, identyfikatorów, znaczników czasu ani numerów linii: wzorzec
ma przeżyć przeformatowanie testu.

`Wyjatek(...)` dopuszcza wyjątek (`<error>`) jako objaw tej mutacji — tylko tam,
gdzie sama mutacja go powoduje (przerwana transakcja, niespełniona atrapa);
wzorzec ma wtedy wskazać klasę wyjątku i treść.

Kontrola bez wpisu przechodzi jako BEZ_WZORCA i jest wymieniona z nazwy w
podsumowaniu: to dowód niepełny (docs/PULAPKI_TESTOW.md §5b).

Ten moduł nie zawiera nazw żadnych testów projektu w cudzysłowie: strażnik
`StraznikTekstuMaKontroleDodatniaTest` czyta pliki `scripts/*.py` i uznałby
taką nazwę za pokrycie.
"""

from kontrola_przyczyny import Wyjatek


# #2167: brak wymaganego CSV ma oblać test własnym komunikatem, nie skipem.
OCZEKUJ_MIARY = r'Brak wymaganego pliku database/data/odzywcze/miary\.csv'

OCZEKUJ_GRAF_CYKLI = r'Graf zależności modułów app/Domain zmienił swoje cykle'

OCZEKUJ = {
    'Dokumentacja bazy wraca do martwej lokalnej kotwicy': r'BAZA_KOTWICA_20261003',
    'Kopia odzyskania gubi ręczną kolejność (#2816)': r'ODZYSKANIE_2816_RECZNA_KOLEJNOSC',
    'Odtworzenie zeszytu gubi ręczną kolejność (#2816)': r'ODZYSKANIE_2816_RECZNA_KOLEJNOSC',
    'Ponowienie zaproszenia ujawnia nazwę po odebraniu dostępu (#2825)': r'ZESZYT_2825_PONOWIENIE_BEZ_DOSTEPU',
    'Zawieszona autorka nie może cofnąć udostępnienia (#2791)': r'UDOSTEPNIENIE_2791_COFNIECIE_MIMO_KARY',
    'Moje rozmowy przepuszczają niemożliwą datę kursora (#2803)': r'ROZMOWY_2803_NIEMOZLIWY_CZAS',
    'Ponowienie przeniesienia ujawnia niedostępny tytuł (#2809)': r'PRZENIESIENIE_2809_TYTUL_POD_POLICY',
    'Moje rozmowy pomijają Policy wpisu (#2432)': r'ROZMOWY_2432_POLICY_TRESCI',
    'Import odrzuca ułamek czasu bez ostrzeżenia (#2546)': r'IMPORT_2546_CZAS_WIDOCZNY',
    'Import nie zapisuje ostrzeżeń parsera przy szkicu (#2548)': r'IMPORT_2548_OSTRZEZENIE_TRWA',
    'Importowany szkic traci bramkę odczytu w kopii (#2800)': r'KOPIA_2800_IMPORT_OMINIETY',
    'Spiżarnia: jedyne opakowanie bez odcisku (#2783)': r'ODCISK_2783_FORMULARZ',
    'Spiżarnia: identyczne B bez kontroli tożsamości (#2783)': r'ODCISK_2783_TOZSAMOSC',
    'Niezmieniona kopia szkicu wychodzi do ludzi (#2507)': r'KOPIA_2507_PUBLIKACJA',
    'Kopia szkicu gubi podpis Mojej wersji (#2507)': r'KOPIA_2507_ATRYBUCJA',
    'Kopia szkicu przejmuje zdjęcia kroków (#2507)': r'KOPIA_2507_MEDIA',
    'Kopia szkicu ocenia prawo na starym stanie (#2507)': r'KOPIA_2507_SWIEZY_STAN',
    'Kopię cudzego szkicu zrobi każdy (#2507)': r'KOPIA_2507_WLASCICIEL',
    'Kolaż hero bez podpisu autora przy zdjęciu (#2708)': r'Kafel nie ma podpisu z nazwą dokładnie jednego autora',
    'Dołączenie zdjęcia: podmiana UUID kucharza (#2500)': r'DOLACZENIE_2500_PODMIANA_UUID',
    'Ponowiony multipart zapisuje osierocone zdjęcie (#2811)': r'DOLACZENIE_2811_BEZ_OSIEROCONEGO_MEDIA',
    'Historia zdjęć urywa się po szóstym wysłaniu (#2811)': r'DOLACZENIE_2811_SIODME_WYSLANIE_PO_USUNIECIU',
    'Wymazanie zostawia prywatne klucze zdjęć (#2811)': r'DOLACZENIE_2811_WYMAZANE_KLUCZE',
    'Dołączenie zdjęcia liczy limit bez przypiętych (#2500)': r'DOLACZENIE_2500_LIMIT',
    'Dołączenie zdjęcia ignoruje świeży stan pod blokadą (#2500)': r'DOLACZENIE_2500_SWIEZY_STAN',
    'Dołączenie zdjęcia przejmuje cudze albo cudzo-przypięte (#2500)': r'DOLACZENIE_2500_WLASNOSC_MEDIOW',
    'Rollback udostępnień przepisów kasuje bez pytania (#2650)': r'Rollback skasował udostępnienia bez pytania',
    'Eksport pobiera tytuł przepisu bez aktualnego dostępu (#2785)': r'EKSPORT_2785_BIEZACY_TYTUL_BEZ_DOSTEPU',
    'Instrukcja CSAM myli awatar i osobne zdjęcie z nieobsługiwanymi (#2708)': r'CSAM_2708_MEDIA_NIE_SA_POZA_ZAKRESEM',
    'Tabela CSAM wraca do starej instrukcji zgłoszenia (#2708)': r'CSAM_2708_TABELA_ZGODNA_Z_EKRANEM',
    'Udostępnienie przechodzi na nowego właściciela nazwy (#2790)': r'ODBIORCA_2790_NIE_PRZECHODZI_NA_NOWE_KONTO',
    'Listy zakupów mieszają pozycje (#2528)': r'LISTY_2528_POZYCJE_NIE_MIESZAJA_SIE',
    'Cudza lista zakupów otwiera ekran i przyjmuje zapis (#2528)': r'LISTY_2528_CUDZA_LISTA_ODMOWA',
    'Usunięcie listy ignoruje zmienioną liczbę pozycji (#2528)': r'LISTY_2528_USUNIECIE_NIEAKTUALNA_LICZBA',
    'Lista ostatnio oglądanych sięga do analityki (#2553)': r'OSTATNIO_OGLADANE_2553_PRYWATNA_LISTA_POZA_ZAMKNIETA_LISTA',
    'Lista ostatnio oglądanych pokazuje przepis konta zbanowanego (#2553)': r'OSTATNIO_OGLADANE_2553_TYTUL_NIEDOSTEPNEGO_PRZEPISU',
    'Lista ostatnio oglądanych miesza konta (#2553)': r'OSTATNIO_OGLADANE_2553_KONTO_[AB]_WIDZI_LISTE_[AB]',
    'Domyslny JIT wraca na polaczeniu PostgreSQL (#2291)': r'JIT_2291_SWIEZA_SESJA_WYMAGA_OFF',
    "Pusta linia Unicode tworzy składnik (#2621)": r'PUSTE_LINIE_2621_UNICODE',
    "Pusta linia Unicode skleja kroki po POST (#2621)": r'PUSTE_LINIE_2621_POST_KROKI',
    "Co ugotuję: ostatnia strona wraca do siebie (#2599)": r'PAGINACJA_2599_BEZ_PETLI',
    "Co ugotuję: pusty termin myli się z pustym zeszytem (#2591)": r'ZESZYTY_2591_PUSTY_PILNY_ZAKRES',
    "HTTP import paczki nie pilnuje budżetu struktury (#2611)": r'BUDZET_2611_HTTP_ODMOWA',
    "Paczka JSON bez budżetu struktury (#2611)": r'BUDZET_2611_ODMOWA_BEZ_FATALA',
    "Porcje mnożą procent tłuszczu (#2629)": r'PORCJE_2629_PROCENT_NIE_JEST_ILOSCIA',
    'Mikrodane ListItem zastępują instrukcję etykietą (#2638)': r'MICRODATA_2638_ITEM_PRZED_ETYKIETA',
    'Mikrodane pusty ListItem zgaduje instrukcję (#2638)': r'MICRODATA_2638_PUSTY_ITEM_BEZ_ZGADYWANIA',
    'Mikrodane ListItem zapisują etykietę do szkicu (#2638)': r'MICRODATA_2638_HTTP_ITEM',
    'Import URL: regex zostawia potomka komentarzy (#2640)': r'IMPORT_2640_CALE_PODDRZEWO',
    'Import URL HTTP: regex wysyła komentarz do fragmentów (#2640)': r'IMPORT_2640_HTTP_BEZ_KOMENTARZY',
    'OCR: miesięczny limit obiecuje jutro (#2648)': r'OCR_2648_MIESIAC_NIE_OBIECUJE_JUTRA',
    'PDF: ilość dziesiętna staje się numerem listy (#2614)': r'PDF_2614_ILOSC_DZIESIETNA_NIE_JEST_NUMEREM_LISTY',
    'Identyfikator JSON-LD udaje krok (#2582)': r'JSONLD_ID_KROKU_NIE_JEST_TEKSTEM',
    'ListItem.item nie trafia do szkicu importu (#2570)': r'JSONLD_LISTITEM_ITEM_ZAPISUJE_KROKI',
    'Literalne porównanie znika z instrukcji JSON-LD (#2580)': r'IMPORT_2580_POROWNANIE_NIE_UCINA',
    'Zakodowane podziały JSON-LD sklejają instrukcje (#2564)': r'IMPORT_2564_(?:KROKI|SKLADNIKI)_BEZ_SKLEJANIA',
    'Odtworzony markup JSON-LD zostaje w zwykłym tekście (#2564)': r'IMPORT_2564_MARKUP_NIE_JEST_TEKSTEM',
    'JSON-LD dekoduje więcej niż dwie warstwy (#2564)': r'IMPORT_2564_TYLKO_DWIE_WARSTWY',
    'Koszt: druga ilość wraca do wyceny pierwszej (#2578)': r'KOSZT_2578_DRUGA_ILOSC_NIE_ZANIZA_MASY',
    'Koszt: dopełniacz miary staje się sztuką (#2643)': r'KOSZT_2643_DOPELNIACZ_MIARY_NIE_JEST_SZTUKA',
    'Koszt: grupowane tysiące stają się sztukami (#2561)': r'KOSZT_2561_GRUPOWANE_TYSIACE_NIE_SA_SZTUKAMI',
    "Prywatny zeszyt obiecuje odebranie dostepu (#2601)": r"ZESZYT_2601_PRYWATNY_NIE_ODBIERA_ZAPROSZONYM",
    'OCR: błąd zdjęcia znika z opisu pola (#2586)': r'OCR_2586_BLEDNY_OPIS_POLA',
    'Odżywcze: inny surowiec trafia w mąkę pszenną (#2607)': r'SUROWIEC_2607_NIE_POMIJAJ_ZRODLA',
    'Odżywcze: stan przed nazwą znika (#2563)': r'STAN_2563_PRZED_NAZWA',
    'Odżywcze: stan po nazwie znika (#2563)': r'STAN_2563_PO_NAZWIE',
    "Spiżarnia: sól z 'bez soli' udaje masło (#2613)": r'SPIZARNIA_2613_SOL_NIE_JEST_MASLEM',
    "Porcje: Mniej od autora prowadzi do odrzucanej liczby (#2624)": r'PORCJE_2624_MNIEJ_BEZ_PETLI',
    'Robots: awaria PCRE nie daje zgody (#2617)': r'ROBOTS_2617_AWARIA_PCRE_NIE_JEST_ZGODA',
    'Robots: zakodowane litery omijają zakaz (#2569)': r'ROBOTS_2569_OKTETY_ZAKAZANE',
    'Robots: znaki zarezerwowane dekodowane bez ograniczenia (#2569)': r'ROBOTS_2569_BEZ_PONOWNEGO_DEKODOWANIA',
    'Robots: długość kodowania wygrywa nad oktetami (#2569)': r'ROBOTS_2569_DLUGOSC_OKTETOW',
    "Spiżarnia usuwa bez pytania (#2467)": r'SPIZARNIA_2467_USUNIECIE_WYMAGA_PYTANIA',
    "Stare potwierdzenie spiżarni kasuje dodane opakowanie (#2826)": r'SPIZARNIA_2826_STARE_POTWIERDZENIE_NIE_KASUJE',
    "Stare potwierdzenie A kasuje awansowane B (#2826)": r'SPIZARNIA_2826_AWANS_B_NIE_KASUJE',
    'Planer usuwa bez pytania (#2468)': r'PLANER_2468_PIERWSZY_KLIK_BEZ_DELETE',
    "Zmiana porcji zachowuje stare odmierzenie (#2502)": r'PORCJE_2502_NOWA_ILOSC_NIE_PRZYGOTOWANA',
    "Stary formularz przywraca porcje z innego urządzenia (#2502)": r'PORCJE_2502_STARY_FORMULARZ_NIE_PRZYWRACA',
    "Powrót porcji ABA przywraca stare odmierzenie (#2502)": r'PORCJE_2502_ABA_NIE_PRZYWRACA',
    "Stary formularz po ponownym włączeniu postępu (#2502)": r'PORCJE_2502_NOWY_POSTEP_NIE_PRZYWRACA',
    'Moje wpisy: stara strona udaje pusty dorobek (#2473)': r'MOJE_WPISY_2473_STARA_STRONA_WRACA',
    'Zapamiętane gotowanie: 500 ukrytych wypiera dostępne (#2439)': r'ZAPAMIETANE_2439_PIERWSZA_PO_500',
    'Moje wpisy: pusta porcja traci kontener (#2473)': r'MOJE_WPISY_2473_PUSTA_PORCJA_MA_LISTE',
    'OCR ignoruje ręczną edycję przed modelem (#2520)': r'REWIZJA_SZKICU_2520_PRZED_MODELEM_',
    'OCR nadpisuje ręczną edycję po odpowiedzi (#2520)': r'REWIZJA_SZKICU_2520_PO_MODELU_',
    'OCR ponawia odczyt zmienionego szkicu (#2520)': r'REWIZJA_SZKICU_2520_BEZ_PONOWIENIA',
    'Odżywcze: grupowana masa traci tysiące (#2560)': r'ODZYWCZE_2560_GRUPOWANA_MASA',
    'Odżywcze: błędna grupa jest częściową masą (#2560)': r'ODZYWCZE_2560_BLAD_GRUPOWANIA_ODMAWIA',
    'Odżywcze: błędna masa bierze miarę puszki (#2560)': r'ODZYWCZE_2560_BLAD_GRUPOWANIA_ODMAWIA',
    'Odżywcze: masa razem mnożona przez puszki (#2487)': r'ODZYWCZE_2487_LACZNA_MASA_BEZ_MNOZENIA',
    'Odżywcze: sprzeczna masa wpada w domyślną miarę (#2487)': r'ODZYWCZE_2487_SPRZECZNY_NAWIAS_ODMAWIA',
    'Sam skan bez notatki znika ze strony przepisu': r'Sam skan musi otwierać sekcję pochodzenia przepisu\.',
    'Pusta dalsza porcja powiadomień bez listy (#2807)': r'POWIADOMIENIA_2807_PUSTA_PORCJA',
    'Pomiar panelu tylko w części 2 (#2446)': r'PANEL_2446_POMIAR_KAZDA_CZESC',
    'Dyktowanie odbiera mikrofon zalogowanemu (#2377 etap 2)': r'DICTATION_AUTH_HEADER',
    'Dyktowanie daje mikrofon gościowi (#2377 etap 2)': r'DICTATION_GUEST_HEADER',
    'Dyktowanie daje mikrofon błędowi i JSON (#2377 etap 2)': r'DICTATION_NON_FORM_RESPONSE',
    'Dyktowanie odblokowuje wszystkie trasy (#2377 etap 2)': r'DICTATION_OTHER_ROUTE',
    'Wspólna sesja traci zamiennik autora (#2485)': r'WSPOLNE_2485_ZAMIENNIK_PRZY_SKLADNIKU',
    'Wspólna sesja traci zdjęcie kroku (#2486)': r'WSPOLNE_2486_ZDJECIE_PRZY_KROKU',
    'Historia ignoruje wybór Bez ilości (#2449)': r'HISTORIA_BEZ_ILOSCI_ZMIANA',
    'Historia zgaduje wybór w starej migawce (#2449)': r'HISTORIA_BEZ_ILOSCI_BRAK_DANYCH',
    'Grupowanie tysięcy rozbite na fragmenty (#2455)': r'GRUPOWANIE_TYSIECY_WYNIK',
    'Pasteryzacja wraca do słownika bez przeglądu (#2434)': r'PASTERYZACJA_USUNIETA_DO_PRZEGLADU',
    'Sparzyć znów łapie oparzenie (#2343)': r'SLOWNIK_RDZEN_INNE_ZNACZENIE',
    'Zaprawić zupę znów łapie przetwory (#2343)': r'SLOWNIK_RDZEN_INNE_ZNACZENIE',
    'Karmelizowana cebula trafia w karmel z cukru (#2343)': r'SLOWNIK_KARMEL_ROZDZIELONY',
    'Marynowanie bez lodówki (#2343)': r'SLOWNIK_MARYNOWANIE_W_LODOWCE',
    'Uwaga słownika gwarantuje parametry autora (#2434)': r'PASTERYZACJA_UWAGA_NIE_GWARANTUJE',
    # Paczka V: kontrole dodatnie trzech strażników tekstu.
    'Pasek przy kolumnowym znaku znowu przypięty': r'Przy progu układu kolumnowego znaku pasek ma przestać być przypięty\.',
    'Uwaga słownika terminów wraca do .meta': r'Uwaga pod słownikiem terminów zeszła do \.meta albo poniżej 18 px',
    'Przełącznik rejestracji bez Shared Variable': r'Bez referencji `ctx\.shared` zamknięcie rejestracji z panelu zniknie przy pierwszym `apply`\.',
    'Fixture wspomnienia znika po północy w Polsce': r'POMIAR_WSPOMNIENIA_PRZED_I_PO_POLNOCY',
    "Koszt autora pozostaje bazowy po zmianie porcji (#2524)": r'KOSZT_AUTORA_2524_NIEPRZELICZONY',
    'Pusty Recipe zasłania pełny w JSON-LD (#2536)': r'JSONLD_PUSTY_NIE_ZASLANIA',
    'Meta content składnika znika z mikrodanych (#2538)': r'MICRODATA_META_SKLADNIK',
    'Meta content kroku znika z mikrodanych (#2538)': r'MICRODATA_META_KROK',
    'Meta content zagnieżdżonego kroku znika (#2538)': r'MICRODATA_META_KROK',
    'Alias składnika powiela jeden węzeł (#2626)': r'MICRODATA_2626_SKLADNIK',
    'Alias kroku powiela jeden węzeł (#2626)': r'MICRODATA_2626_KROK',
    'Tekstowe ułamkowe porcje znikają (#2539)': r'PORCJE_ULAMKOWE_TEKST',
    'Porcje numeryczne poza granicami formularza (#2539)': r'PORCJE_NUMERYCZNE_ZGODNE_Z_FORMULARZEM',
    'Koszt: opis celu kasuje rozpoznaną masę (#2508)': r'KOSZT_2508_OPIS_CELU_NIE_KASUJE_MASY',
    'Koszt: słowny zakres gubi granice i miarę (#2477)': r'KOSZT_2477_SLOWNY_ZAKRES_ZACHOWUJE_GRANICE_I_MIARE',
    'Koszt: uszkodzony zakres przyjmuje początek (#2477)': r'KOSZT_2477_USZKODZONY_ZAKRES_NIE_LICZY_POCZATKU',
    'Koszt: uszkodzona pojedyncza liczba daje wycenę (#2477)': r'KOSZT_2477_USZKODZONA_JEDNA_LICZBA_NIE_DAJE_WYCENY',
    'Koszt: mąka gryczana udaje kaszę (#2605)': r'KOSZT_2605_MAKA_NIE_JEST_KASZA|KOSZT_2605_MAKA_NIE_DAJE_POKRYCIA',
    'Szyna zeszytu ponownie czyta całą historię (#2030)': r'SZYNA_2030_CALA_HISTORIA',
    'Przeterminowany use_by wraca do doboru (#2453)': r'USE_BY_2453_BEZ_DOBORU',
    'Przeterminowany use_by wybiera odbiorcę listu (#2453)': r'ODBIORCA_2453_BEZ_PRZETERMINOWANEGO_USE_BY',
    'Bieżący eksport pomija wybór Bez ilości (#2476)': r'EKSPORT_BIEZACY_BEZ_ILOSCI',
    'Eksport gubi relację wykonania z własnym przepisem (#2639)': r'EKSPORT_2639_RELACJA_WYKONANIA_DO_PLIKU',
    'Eksport planu zdjęć ładuje autora przepisu (#2639)': r'EKSPORT_2639_PLAN_ZDJEC_BEZ_LENIWEGO_AUTORA',
    'Ukryty przepis nazwany szkicem w eksporcie (#2479)': r'EKSPORT_UKRYTY_NIE_JEST_SZKICEM',
    'Sam rok rodzinny znika z HTML eksportu (#2478)': r'EKSPORT_ROK_SAM_W_HTML',
    # #1011, paczka H: wpisy dopisane po wzorcach dla wcześniejszych kontroli.
    "Goły ->with('status') wraca do kontrolera": r'Goły zapis klucza `status` wygląda jak zielony sukces',
    'Odmowa nazwana sukcesem': r'Komunikat::sukces\(\) z tekstem „Nie udało się…" — to błąd, nie sukces\.',
    'Produkcja dostaje domenę dostawcy obok kuking.pl': r'PROD_DOMAINS w \.railway/railway\.ts przestało być zbiorem|PROD_DOMAINS zawiera domenę „[^”]+” spoza kuking\.pl',
    'Rejestracja wdrożenia wraca do preDeployCommand': r'preDeployCommand kończy się PRZED startem i healthcheckiem nowego kontenera — rejestracja tam zużywa numer',
    'Entrypoint rejestruje wdrożenie bez czekania na /health': r'Funkcja musi wołać komendę z --po-gotowosci',
    'Import z adresu publikuje przepis': r'\S+ publikuje przepis\.',
    # #1011, paczka G: wpisy dopisane po wzorcach dla pierwszych 219 kontroli.
    'Kreator pozwala klientowi podmienić recipeId': r'CannotUpdateLockedPropertyException" is thrown',
    'Kreator nie wysyła oczekiwanej rewizji treści': r"-'error' \+'saved'",
    'Publikacja cofa z podglądu przy błędzie przepisu': r'Failed asserting that 3 matches expected 4\.',
    'Wygenerowany font bez glifu „ą"': r'Brak glifu w podzbiorze Inter: ą \(U\+0105\)',
    'Analytics znowu importuje Compliance': OCZEKUJ_GRAF_CYKLI + r'|Analytics importuje App\\Domain\\Compliance',
    'Media znowu importuje Moderation': OCZEKUJ_GRAF_CYKLI + r'|Media importuje App\\Domain\\Moderation',
    'Compliance znowu importuje Moderation': OCZEKUJ_GRAF_CYKLI + r'|Compliance importuje App\\Domain\\Moderation',
    'Moderation znowu importuje Security': OCZEKUJ_GRAF_CYKLI + r'|Moderation importuje App\\Domain\\Security',
    'Nowy cykl: Users importuje Moderation (Moderation → Users już jest)': OCZEKUJ_GRAF_CYKLI,
    'Formularz zeszytu sprawdza pola przed Policy': r'Expected response status code \[403\] but received 302\.',
    'Wymazanie nie wycofuje wpisu dziennika po nieudanym commicie': r"\+ 'user_id' => '[0-9a-f-]+', \+ 'wymazano_at' =>",
    'Wymazanie kasuje cudzy wpis dziennika (ISTNIEJE)': r"-Array &0 \[ - 0 => '[0-9a-f-]+', -\] \+Array &0 \[\]",
    'Zapis dziennika czeka wewnątrz transakcji z blokadą konta': r'- 0 => 1, - 1 => 1, \+ 0 => 2, \+ 1 => 2,',
    'Egzekutor nie liczy porażek dziennika wymazań': r'Failed asserting that 0 is identical to 1\.',
    'Alarm dziennika wymazań bez zerowania licznika': r"'noce' => 2, 'dzien' => '[0-9-]+', \] is null\.",
    'Alarm dziennika wymazań liczy każdy przebieg dnia jako noc': r'Failed asserting that 3 is identical to 1\.',
    # Mutacja wysyła 181-znakowy tytuł prosto do bazy — objawem jest odmowa
    # kolumny varchar(180), a nie asercja testu.
    'Autozapis kreatora zapisuje bez walidacji pól': Wyjatek(r'value too long for type character varying\(180\).*insert into "recipes"'),
    'Sufit paczki importu wraca do 32 MB': r'BUDZET_1985_DANE_MAX_12_MB',
    'Nowe konto Google gubi powrót do rozmowy': r'Expected response status code \[201, 301, 302, 303, 307, 308\] but received 200\.',
    'Nowe konto Facebook gubi powrót do rozmowy': r'Expected response status code \[201, 301, 302, 303, 307, 308\] but received 200\.',
    'Rejestracja hasłem gubi zaproszenie do zeszytu (#2420)': r'ZESZYT_2420_POWROT_PO_REJESTRACJI',
    'Nowe konto Google gubi zaproszenie do zeszytu (#2420)': r'ZESZYT_2420_GOOGLE_NOWE_KONTO',
    'Nowe konto Facebook gubi zaproszenie do zeszytu (#2420)': r'ZESZYT_2420_FACEBOOK_NOWE_KONTO',
    'APT install bez migawki': r'Instalacja pakietów APT bez przypięcia do migawki \(audyt, issue #',
    'Rollback aktywnych ukryć przestaje odmawiać': r'contains "1 aktywnych ukryć"',
    'Composer błędnie deklaruje MIT': r"@@ @@ -'proprietary' \+'MIT'",
    'LICENSE traci zastrzeżenie praw': r'contains "Wszelkie prawa zastrzeżone"',
    'Obraz błędnie deklaruje MIT': r'LABEL org.{1,2}opencontainers.{1,2}image.{1,2}licenses="proprietary"',
    'Format UUID': r'Expected response status code \[201, 301, 302, 303, 307, 308\] but received 500\.',
    'Kolejka zgłoszeń wraca do links()': r'Pod kolejką 26 zgłoszeń nie ma przycisku do strony 2\.|pages/admin/reports\.blade\.php: `links\(\)` renderuje widok Tailwinda',
    'Własność zeszytu': r'Expected response status code \[201, 301, 302, 303, 307, 308\] but received 404\.',
    'Komunikat po powrocie': r'Po powrocie na stronę główną błąd musi być widoczny\.',
    'Podpis co najmniej 18 px': r'Podpis kafla zszedł z minimum 18 px \(`--text-body`, issue #478\)\.',
    'Obwódka listy wyglądu poniżej 3:1': r'jasny: obwódka --color-border na tle panelu \(--color-surface-raised\)',
    'Piąty selektor powołuje się na D-262': r'Na D-262 powołuje się inny zbiór reguł CSS niż cztery selektory z',
    'Akcja GitHuba na ruchomym tagu': r'Zewnętrzna akcja bez pełnego SHA — tag jest ruchomy, więc ten sam',
    'Test skryptu Pythona bez kroku w CI': r'Test skryptu Pythona bez kroku w workflowie — nikt go nie uruchamia w CI',
    'Test przyrządu obciążenia bez kroku w CI': r'Bez kroku: docs/obciazenie/test_connection\.py',
    'Licznik w widocznym menu konta': r'Wejście do panelu nie pokazuje sumy wszystkich kolejek\.',
    'Strażnik tekstu bez własnego wpisu': r'Nowy test czyta źródła i asertuje na ich treści, więc może kiedyś',
    'Odstępstwo bez znacznika': r'Nowy test czyta źródła i asertuje na ich treści, więc może kiedyś',
    'Plik z node --test nieskopiowany do etapu assets': r'Etap `assets` w Dockerfile nie kopiuje',
    'Zdjęcie CHECK-a 2FA przed strażnikiem cofnięcia': r'Sprawdzenie stoi PO zdjęciu CHECK-a — schemat przestaje pilnować',
    'Pierwszy ekran opłacony mniejszym pismem': r'Blok pierwszego ekranu rusza `font-size` — a miał ruszać wyłącznie',
    'Strażnik sekretów osłabiony do samego https': r'Failed asserting that true is false\.',
    'Strażnik sekretów bez sprawdzenia ścieżki': r'Failed asserting that true is false\.',
    'Komunikat bazy z wartościami w logu serwera': r'does not contain "basia\.kowalska@example\.com"',
    'Błąd PCRE w filtrze logu po cichu zeruje treść': r'starts with "\[treść usunięta z logu: filtr danych osobowych nie dał rady\]"',
    'Filtr logu na loggerze zabiera webhookowi obiekt wyjątku': r'contains "Illuminate\\\\Database\\\\UniqueConstraintViolationException"',
    'Surowy komunikat wyjątku w logu kasowania zdjęcia': r'does not contain "basia@example\.com"|Surowe getMessage\(\) w logu \(użyj BezpiecznyBlad::kontekst\(\)\)',
    'Wzorzec e-maila z katastrofalnym nawracaniem': r'does not contain "\[treść usunięta z logu: filtr danych osobowych nie dał rady\]"',
    'Klucz tablicy z adresem przechodzi do logu': r'does not contain "basia\.kowalska@example\.com"',
    'Obiekt w kontekście logu idzie do formatera w całości': r'does not contain "basia\.kowalska@example\.com"',
    'Za głęboka tablica przechodzi surowa': 'contains "\\[pominięte: zagnieżdżenie głębsze niż filtr sprawdza\\]"|@@ @@ Array &0 \\[ - 0 => \'poziom\', \\+ 0 => \'e\', \\]',
    'Połknięty wyjątek bez miejsca przyczyny': r"@@ @@ Array &0 \[ - 0 => 'app/Support/PhpIniRozmiar\.php:\d+', \+ 0 => null, \]",
    'Komunikat wyjątku w kontekście budowanym przez metodę pomocniczą': r'Surowe getMessage\(\) w logu \(użyj BezpiecznyBlad::kontekst\(\)\)',
    'Komunikat transportu przez BezpiecznyKomunikat w logu listu o paczce': r'does not contain "insert into"|does not contain "\$2y\$"|does not contain "X-Amz-Signature"|Surowe getMessage\(\) w logu \(użyj BezpiecznyBlad::kontekst\(\)\)',
    'Komunikat bazy przez BezpiecznyKomunikat w logu śladu listu': r'does not contain "insert into"|does not contain "\$2y\$"|does not contain "X-Amz-Signature"|Surowe getMessage\(\) w logu \(użyj BezpiecznyBlad::kontekst\(\)\)',
    'Skaner logów ślepy na report()': r'Skaner nie złapał wszystkich form: Naruszenia\.php:6 Naruszenia\.php:7',
    'Kolor z niezdefiniowanej zmiennej': r'Te zmienne kolorów są użyte, ale nigdzie nie zdefiniowane',
    'Rama marki z zaszytym kolorem': r'Te kolory są wpisane w regułę zamiast w token',
    'Bramka R2 każe sprawdzać Sentry (#2382)': r'Sentry może wystąpić tylko jako wyraźnie oznaczony plan',
    'Linki sąsiednich wpisów bez skali tekstu': r'contains "font-size: var\(--text-body\)"',
    'Cofnięcie CHECK-a kontaktu bez odmowy przy sierotach': r"contains 'Nie można cofnąć migracji'",
    'Cofnięcie znaczników odpowiedzi bez odmowy': r'exception of type "RuntimeException" is thrown',
    'Jedna sprawa RODO w toku bez odmowy przy duplikatach': r'contains "Liczba kont z więcej niż jedną otwartą sprawą RODO',
    'Lokalne akcje poza filtrem widoku': r'Bramka pomija job `\w+` przy zmianie `\.github/actions/[^`]+`, a ten job tej akcji UŻYWA',
    'Dockerfile poza wzorcem builda obrazu': r'Bramka pomija job `docker-build` na PR-ze przy zmianie `Dockerfile`',
    'Pliki grupy wyścigów poza wzorcem joba': r'Bramka pomija job `dwa-polaczenia` na PR-ze przy zmianie',
    'Ciężkie joby zawężane także poza PR-em': r'Job `przyrzad_605` jest pomijany poza PR-em \(zdarzenie: push\)\. Na',
    'Wzorzec przyrządu #605 łapie każdą zmianę': r'Bramka uruchamia `przyrzad_605` na PR-ze przy zmianie',
    'Filtr widoku zawężany także poza PR-em': r'zakres: filtr widoku zawęża poza PR-em \(zdarzenie: push\)\.',
    'Podział wierszy przez \\R bez u': r'Wzorzec z `\\R` bez modyfikatora `u` tnie „ą',
    'Test dymny przepuszcza każde przekierowanie': r'contains "sonda_https "',
    'Test dymny bez sondy wydania przed sprawdzeniami': r'Test dymny nie potwierdza, że pod adresem działa wdrażany commit \(#',
    'Końcowa sonda wydania z jedną próbą': r'Po sprawdzeniach wydanie trzeba potwierdzić jeszcze raz — mogło się',
    'Akcja rollback, która nic nie cofa': r"contains 'instrukcja-cofniecia'",
    'Preview gotowe po samym adresie': r'Krok czekania nie woła czekaj_na_preview dla SHA z PR-a\.',
    'Preview bez sondy wydania przed sprawdzeniami': r'Test dymny preview nie pyta /wydanie o commit PR-a \(#',
    'Job smoke znów dostaje prawo zapisu do PR-ów (#1941)': r'Job „smoke” uruchamia kod z PR-a i NIE MOŻE dostać `pull-requests',
    'Apply IaC bez przekazanej bramki CI': r'Job „apply” nie przekazuje KUKING_WAIT_FOR_CI — railway\.ts policzy',
    'Brak KUKING_WAIT_FOR_CI jako wyłączenie': r'railway\.ts ma odmówić przy braku albo złej wartości',
    '/wydanie z sesją i ciasteczkami': r'`/wydanie` stawia ciasteczka\.',
    'Obraz bazowy bez digestu': r'Obraz bazowy bez digestu — tag jest ruchomy, więc build nie jest',
    'Oryginał zdjęcia z nietkniętym XMP': r'W xmp-gps\.jpg został pakiet XMP\.|W xmp-gps\.png został pakiet XMP\.|W xmp-gps-skompresowany\.png został pakiet XMP\.|W xmp-gps\.webp został pakiet XMP\.|W xmp-gps\.avif został pakiet XMP\.|Failed asserting that|Oryginał leży w buckecie z pakietem XMP\.',
    'Sekret OAuth w workerze': r'Rola `worker` dostaje w `railway\.ts` sekrety spoza swojej macierzy|`worker` nie obsługuje logowania ani formularzy, a dostaje',
    'Worker bez klucza moderacji modelem': r'`config/\*\.php` czyta te zmienne bez wartości domyślnej, a|Rola `worker` nie dostaje w `railway\.ts`: OPENAI_MODERATION_KEY\. Kod|Worker wykonuje `PrzeanalizujTresc` i bez klucza moderacja modelem|Nie znalazłem w żadnej roli którejś ze zmiennych TYLKO_PRODUKCJA —',
    'Scheduler bez adresu alarmów moderacji': r'Rola `scheduler` nie dostaje w `railway\.ts`|Scheduler uruchamia podsumowanie automatu i pilnowanie terminów',
    'Web bez adresu alarmów moderacji': r'Rola `web` nie dostaje w `railway\.ts`: KUKING_MODEL_ALARM_EMAIL\. Kod|Web woła `AlarmujOPilnymZgloszeniu` synchronicznie w żądaniu',
    'Klucz modelu bez warunku produkcji': r'Rola `all` dostaje OPENAI_MODERATION_KEY bez warunku `isProduction \?',
    'Adres alarmu bez warunku produkcji': r'Rola `web` dostaje KUKING_MODEL_ALARM_EMAIL bez warunku `isProduction',
    'Scheduler bez kluczy poczty przy digeście': r'Scheduler uruchamia w swoim procesie komendy, które budują mailer',
    'Kopia bazy ze spreadem zestawu aplikacji': r'Serwis `kopia-bazy` ma zamkniętą listę zmiennych \(#193\)\. Żaden zestaw',
    'Polityka znowu obiecuje pełną kopię': r'Polityka znowu obiecuje „pełną kopię',
    'Polityka przestaje wymieniać obserwowane tagi': r'contains "jakie tagi obserwujesz"',
    'Polityka gubi prywatność listy „Co mam w domu”': r'contains "widzisz ją tylko Ty"',
    'Godzina w widoku z pominięciem Czas': r'Widok formatuje datę z pominięciem `App\\Support\\Czas` — pokaże czas',
    'Nieudane wgranie bez kompensacji plików': Wyjatek(r'Oryginał został w buckecie bez wiersza `media`|InvalidCountException: Method error\('),
    'Decyzja moderacyjna tworzona poza listą': r'Powstało nowe miejsce tworzące decyzję moderacyjną\. Sprawdź, czy',
    'Polityka bez nazwy ciasteczka motywu': r'Serwis stawia ciasteczko „motyw” \(ważne rok\), a polityka nie podaje',
    'Polityka wiąże dziennik z instancją': r'Polityka znowu wiąże dziennik serwera z życiem instancji\. Railway',
    'Polityka bez liczby dni dziennika': r'Wiersz o błędach technicznych nie podaje, ile dni Railway trzyma',
    'Manifest Vite z rocznym cache assetów': r'contains "@viteAssets path /build/assets/\*"',
    'Trasa ze zdjęciem pod progiem 2 MB w Caddy': r"Trasa `settings\.avatar\.update` \(/ustawienia/zdjecie\) przyjmuje|@@ @@ 1 => '/pytania', 2 => '/przepisy/\*', 3 => '/wpisy/\*', - 4 => '/livewir",
    'Rejestr wyjątków z nieistniejącą klasą': r'REJESTR\[App\\Models\\Comment\]\[author_id\] wskazuje klasę AddComment',
    'Rejestr wyjątków z nieistniejącą stałą': r'REJESTR\[App\\Models\\Report\]\[status\] wskazuje stałą STATUS_NEW, której',
    'Zlecenie zdjęcia poza transakcją wiersza': Wyjatek(r'QueryException: SQLSTATE\[25P02\]: In failed sql transaction|Expected response status code \[201, 301, 302, 303, 307, 308\] but received 500'),
    'Referrer-Policy w Caddy nadpisuje decyzję aplikacji': r'Nagłówek Referrer-Policy ma w aplikacji różne wartości zależnie od',
    'Strażnik R2 bez segmentu eu': r'Przepuszczony: https://',
    'Strażnik R2 bez kotwicy końca': r'Przepuszczony: https://',
    'Ostrzeżenie o zmianie adresu czyta adres przy wysyłce': r'Ostrzeżenie musi trafić do starej skrzynki także po potwierdzeniu',
    'Awans roli bez odwołania sesji': r'Sesja sprzed awansu na moderator weszła do panelu\.|Sesja sprzed awansu przetrwała\.',
    'Wybór kolażu bez kaskady przy odpięciu zdjęcia': r"@@ @@ -'FOREIGN KEY \(post_id, media_id\) REFERENCES post_media\(post_id, media",
    'Landing: podgląd prowadzi do trasy auth': r'Odnośnik „Zobacz, kto może widzieć wpis” \(.*\) nie pokazuje gościowi treści — status 302',
    'Autozapis kreatora #892 bez kroku CI': r'Autozapis #892 nie chodzi w CI: autosave Failed asserting that 0 is',
    'Pomiar #713 paska bez kroku CI': r'Pomiar #713 nie chodzi w CI albo chodzi dwa razy: pasek-uklady Failed asserting that 0 is',
    'Stały token wydania Livewire': r"@@ @@ -'[0-9a-f]{7,40}' \+'a'|@@ @@ -'lokalnie' \+'a'|livewire\.release_token nie czyta RAILWAY_GIT_COMMIT_SHA\.|Migawka ze starego wydania przeszła weryfikację tokenu\.",
    'Kreator obiecuje szkic przed zapisem': r'contains "data-kreator-zapis="',
    'Polityka obiecuje UE przy strażniku bez eu': r'Wiersz Cloudflare R2 obiecuje „Unia Europejska”, ale strażnik',
    'Zapis weryfikacji R2 z inną datą niż polityka': r'Ostatni zapis weryfikacji jurysdykcji R2 jest z',
    'Kontroler znów zleca analizę awatara': r'AvatarSettingsController znów odwołuje się do PrzeanalizujAwatar\.|Dokumenty rozjechały się z kodem awatarów \(D-240, #',
    'DATABASE.md znów mówi, że model ocenia awatar': r'Dokumenty rozjechały się z kodem awatarów \(D-240, #',
    'Indeks bazy gubi plik obszaru': r'Te pliki z docs/baza/ nie są wymienione w docs/DATABASE\.md|docs/DATABASE\.md wskazuje pliki, których nie ma w docs/baza/',
    'Link względny w docs/baza/ bez poprawki po przeniesieniu': r'Linki względne w docs/baza/ liczą się od tego katalogu',
    'Wyjęcie przepisu ze wszystkich zeszytów bez transakcji': r'Po awarii w środku wyjęcia część zapisów zniknęła — wyjęcie nie jest',
    'Wyjęcie wpisu ze wszystkich zeszytów bez transakcji': r'Po awarii w środku wyjęcia część zapisów zniknęła — wyjęcie nie jest',
    'Odwołanie autora bez wspólnej transakcji z zawiadomieniami': r'Pismo zostało złożone mimo niepełnego zawiadomienia zespołu \(#',
    'Odwołanie zgłaszającego bez wspólnej transakcji z zawiadomieniami': r'Pismo zostało złożone mimo niepełnego zawiadomienia zespołu \(#',
    'Reguła zdjęć Cloudflare bez warunku ciasteczka': r'Reguła 0 bez warunku and http\.cookie eq',
    'Timeout blokady funkcji nie oddaje miejsca wspólnej puli': r'Timeout blokady funkcji zostawił zajęte miejsce we wspólnej puli —',
    'Domena importuje Illuminate\\Http\\Request': r'Plik w app/Domain importuje Illuminate.Http\. Wejście HTTP idzie do adaptera|Domena nie zna Request \(#970\)',
    'Zapis przepisu do cudzego zeszytu': r'Akcja zapisała przepis do cudzego zeszytu\.',
    'Zapis wpisu do cudzego zeszytu': r'Akcja zapisała wpis do cudzego zeszytu\.',
    'Podział testów gubi plik': r"Plik tests/\S+ nie trafił do żadnej części — nie uruchamia się NIGDZIE\.",
    'Macierz testów krótsza niż podział': r"@@ @@ -Array &0 \[\] \+Array &0 \[ \+ 0 => 'Skrypt dzieli na 4 części, a macierz ",
    'Wyścigi dwóch połączeń znów nie blokują CI': r'Job `dwa-polaczenia` znów ma continue-on-error',
    # Flaga na jobie `audit` zapala w tej samej klasie także spis dozwolonych
    # `continue-on-error` — dwa objawy jednej mutacji.
    'Audyt zależności znów nie blokuje CI': r'Job `audit` znów ma continue-on-error|Nowe continue-on-error w ci\.yml',
    'Audyt zależności bez skryptu bramki': r'python3 scripts/audyt-zaleznosci\.py',
    'Nowe continue-on-error w jobie testów': r'Nowe continue-on-error w ci\.yml',
    # Macierz [1] (z [1, 2]) pada na pierwszej asercji o liczbie części, zanim
    # dojdzie do porównania z GRUPY — obie są objawem tej samej mutacji.
    'Macierz portu krótsza niż podział grup': r'Macierz nie dzieli niczego\.|Części macierzy `port_funkcje` rozjechały się z GRUPY',
    'Minutnik poza macierzą portu': r'nie idzie w części 2 albo idzie w obu|Warunek wskazuje część spoza macierzy: 3',
    'Runbook znów instaluje Sentry': r'Runbook poza blokiem `<details>` zawiera instalację pakietu Sentry w',
    'Runbook znów wymaga klucza PostHog': r'Runbook zawiera klucz PostHog w tabeli zmiennych lub sekretów \(`\|',
    'Jeden worker ze ścisłym priorytetem kolejek': r'Zadanie z kolejki `media` nie ruszyło w 3 obrotach przy stałej',
    'Rola all z procesem na kolejkę (OOM w 1024 MB)': r"@@ @@ Array &0 \[ 0 => Array &1 \[ 0 => 'high', - 1 => 'default', \], 1 => Arra",
    'Tryb ścisły Eloquent niewłączony': r'Leniwe ładowanie relacji nie jest zablokowane poza produkcją\.|Staging nie wykrywa leniwego ładowania|Failed asserting that exception of type "Illuminate.Database.(Eloquent.)?(LazyLoadingViolationException|MissingAttributeException|MassAssignmentException)" is thrown',
    'Awaria eksportu bez przekazania wyjątku kolejce': r'Job powinien przekazać wyjątek kolejce, żeby zapisała porażkę i mogła',
    'Klucz eksportu z rodzajem': r"is identical to 'zupy i kiszonki'|contains 'na czym sie znam'",
    'Eksport gubi wybór widoczności wartości odżywczych': r"an array has the key 'pokazuj_wartosci_odzywcze'",
    'Rodzaj po „jesteś” na ekranie Google': r'Tekst przypisuje czytelnikowi płeć',
    'Entrypoint bez klucza preview': r'Entrypoint nie woła kuking_klucz_preview\.',
    'Dalsze okno wyszukiwania bez kursora rankingu': r'Dalsze okno powtórzyło już pokazany przepis\.|Dalsze okno pominęło przepis, który nie był jeszcze pokazany\.|Dalsze okno powtórzyło osobę\.',
    'Nieudany dzwonek kupuje ciszę epizodu': r'Failed asserting that false is true\.|Failed asserting that \d+ is identical to 0\.|Zamknięty epizod nie daje ciszy nawrotowi\.|Nieudana próba WYCISZYŁA czujkę|Analog dla kolejki ma tę samą usterkę|actual size 1 matches expected size 2|Odwołanie przepadło razem z pamięcią alarmu',
    'Podzbiór fontu bez „ą"': r'Poza podzbiorem Inter: ą \(U\+|unicode-range w fonts\.css różni się od kontraktu dla inter-',
    'Viewport bez viewport-fit=cover': r'Wspólny meta viewport musi zawierać viewport-fit=cover \(D-260\)\.',
    'Dolna belka bez lewego insetu': r'contains "left: calc\(8px \+ var\(--safe-left\)\);"',
    'Podpowiedź wyglądu bez dolnego insetu': r'Podpowiedź szybkiego wyglądu musi omijać wskaźnik Home\.',
    'Edycja domyślnego zeszytu bez skutku dla przyszłych zapisów': r'contains "i wszystko, co zapiszesz tu później"',
    'Wydruk przepisu z pismem poniżej 12 pt': r'Reguła druku ustawia pismo poniżej 12 pt\.',
    'Główny link wydruku gubi wybrane porcje (#2474)': r'DRUK_PORCJE_HREF: link nie zachował zaakceptowanych porcji\.',
    'Strona przepisu gubi czas kroku (#2484)': r'CZAS_KROKU_STRONA: czas pierwszego kroku zniknął\.',
    'Wydruk zeszytu gubi czas kroku (#2484)': r'CZAS_KROKU_ZESZYT: czas pierwszego kroku zniknął\.',
    'Ściągawka do wydruku z pismem poniżej 16 pt (F4)': r'Ściągawka nie ma w druku progu 16 pt\.',
    'Wydruk dla pomocnika z pismem poniżej 16 pt (#2345)': r'Wydruk dla pomocnika nie ma w druku progu 16 pt\.',
    'Wydruk z widocznym objaśnieniem Zgłoś dla gościa (#2345)': r'Objaśnienie Zgłoś dla gościa nie jest ukryte w każdym wydruku\.',
    'Wydruk dla pomocnika z kodem QR mniejszym niż 3 cm (#2345)': r'Kod QR na kartce dla pomocnika ma mniej niż 3 cm\.',
    'Karta QR z kodem mniejszym niż 9 cm (#2349)': r'Kod QR na papierze ma mniej niż 9 cm\.',
    'Ściągawka bez wspólnej ramy druku (F4)': r'Ściągawka nie dzieli z przepisem ramy kartki w druku\.',
    'Offline: „Spróbuj ponownie” znów prowadzi na /home (#749)': r"@@ @@ -'' \+'/home'",
    'Kontrakt karty bez zdjęcia przepisu': r'Karta dociąga relacje leniwie na powierzchni „obserwowani”\.|Karta dociąga relacje leniwie na powierzchni „tagi”\.|Karta dociąga relacje leniwie na powierzchni „odkrywanie”\.|Karta dociąga relacje leniwie na powierzchni „tablica”\.|Karta dociąga relacje leniwie na powierzchni „profil”\.|Karta dociąga relacje leniwie na powierzchni „tag”\.|Karta dociąga relacje leniwie na powierzchni „zeszyt”\.|Expected response status code \[200\] but received 500\.',
    'Kontrakt karty bez tematów': r'Brak tematów na „obserwowani”\.|Karta dociąga relacje leniwie na powierzchni „tagi”\.|Brak tematów na „odkrywanie”\.|Brak tematów na „profil”\.|Brak tematów na „tag”\.|Brak tematów na „zeszyt”\.',
    'Zamknięcie grupy sygnałów bez porównania liczby': r'Session is missing expected key \[errors\]\.',
    'Zamknięcie grupy sygnałów bez porównania kolejności': r'Session is missing expected key \[errors\]\.',
    'Migracja pierwszych kroków bez backfillu': r'Konto sprzed migracji dostałoby nagle przypomnienie „Dokończ pierwsze|Failed asserting that 2 is identical to 0\.',
    'Koniec pierwszych kroków zapisywany w GET': r'Carbon Object.* is null\.',
    'Turnstile bez porównania hosta': r'WynikTurnstile Enum #\d+ \(Odrzucony\) \+App',
    'Turnstile bez porównania akcji': r'WynikTurnstile Enum #\d+ \(Odrzucony\) \+App',
    'Kolaż hero z lazy na pierwszym kaflu': r'contains "fetchpriority="|kafli: 1 Failed asserting that 0 is identical to 1\.',
    'Polityka z innym terminem usunięcia treści niż konfiguracja': r'contains "najpóźniej \*\*\d+ dni\*\* po usunięciu"',
    'Users znowu importuje Social': r'Graf zależności modułów app/Domain zmienił swoje cykle\. Nowy cykl|app/Domain/Users importuje App\\Domain\\Social',
    'DemoSeeder wypisuje hasło z KUKING_DEMO_HASLO': r'DemoSeeder wypisał hasło z KUKING_DEMO_HASLO\. W CI to wyjście jest',
    'Polityka z okresem sesji innym niż życie sesji na produkcji': r'contains "Do \*\*\d+ dni\*\* od ostatniej aktywności"',
    'Sprzątanie audytu zostawia skrót IP we wpisach dowodowych': r'Failed asserting that 0 is identical to 1\.',
    'Kontroler Google z własną kopią wejścia na konto': r'GoogleLoginController ma własną kopię: wejście na konto \(wpusc /',
    'Operacja na produkcji bierze token staginu, gdy brak sekretu produkcji': r'wyrażenie tokenu Railway daje „tok-staging”, a powinno „”\.',
    'Instalacja Railway CLI bez sprawdzenia sumy kontrolnej': r'\.github/workflows/deploy\.yml: krok „Instalacja Railway CLI” ma',
    'Bramka tokenu krawędzi przepuszcza żądanie bez tokenu': r'Expected response status code \[403\] but received 200\.|Expected response status code \[403\] but received 405\.',
    'Caddy czyta X-Forwarded-For od lewej': r'Dla X-Forwarded-For „198\.51\.100\.66, 203\.0\.113\.7” Caddy zapisze w logu|Dla X-Forwarded-For „192\.0\.2\.1, 198\.51\.100\.66, 203\.0\.113\.7” Caddy|Dla X-Forwarded-For „10\.0\.0\.1, 203\.0\.113\.7” Caddy zapisze w logu',
    'Caddy ufa każdemu peerowi': r'Dla X-Forwarded-For „198\.51\.100\.66, 203\.0\.113\.7” Caddy zapisze w logu|Dla X-Forwarded-For „192\.0\.2\.1, 198\.51\.100\.66, 203\.0\.113\.7” Caddy|Dla X-Forwarded-For „10\.0\.0\.1, 203\.0\.113\.7” Caddy zapisze w logu|Caddy ufa nagłówkowi od peera z adresu publicznego — log opisze adres',
    'Entrypoint czyści cache aplikacji': r'docker/entrypoint\.sh czyści cache aplikacji — to zeruje RateLimiter|cache:clear wyzerował RateLimiter\.',
    'Alarm automatu bez znacznika rezerwacji': r'List z rezerwacją policzony drugi raz\.|Znacznik ListZarezerwowany ma klasa spoza rejestru \(list wypadnie z',
    'Życzenia urodzinowe bez znacznika rezerwacji': r'Życzenia urodzinowe policzone drugi raz: komenda już zajęła miejsce\.|Znacznik ListZarezerwowany ma klasa spoza rejestru \(list wypadnie z',
    'Trasa API bez wiersza w dokumentacji': r"Trasy API bez wiersza w tabeli „Lista endpointów|contains 'GET /api/v1/feed'",
    'Powiadomienie o wykonaniu kucharza w karencji usunięcia': r'Filtr powiadomień \(`WidocznoscTresciSql`\) i Policy odpowiadają',
    'Powiadomienie o komentarzu pod zapowiedzią ukrytego przepisu': r'Filtr powiadomień \(`WidocznoscTresciSql`\) i Policy odpowiadają',
    'Tygodniowy list układa wpisy po liczbie „Ugotowałem”': r'Sortowania niezgodne z §12: - app/Domain/Digest/ZbierzTresciDigestu\.php:\d+ — `orderByDesc\(.cooked_events_count.\)` układa publiczne treści po MIERZE',
    'Mój stół układa przepisy po liczbie „Ugotowałem”': r'Sortowania niezgodne z §12: - app/Domain/Feed/MojStol\.php:\d+ —',
    'Mój stół układa „kuKINGi na dziś” po liczbie „Ugotowałem”': r'Sortowania niezgodne z §12: - app/Domain/Feed/MojStol\.php:\d+ —',
    'Moderacja czyta prywatne ukrycia widzów': r'Ukrycia widza czytane w',
    'Metryki doboru czytają reakcje „Smakowicie wygląda”': r'ukrycia i reakcje nie są źródłem analityki \(D-278, D-280\)',
    'Strona doboru opisuje rotację, której kod nie robi': r'odkrywanie\.rotacja: w app/Domain/Feed/DiscoverFeed\.php nie ma już',
    'Wersja regulaminu podbita bez nagłówka dokumentu': r'Nagłówek regulaminu nie mówi „\d+ \S+',
    'Termin odpowiedzi na reklamację inny niż w regulaminie': r'contains "w ciągu \*\*\d+ dni\*\* od otrzymania reklamacji"',
    'Limit zdjęć we wpisie inny niż w regulaminie': r'Regulamin podaje inną liczbę zdjęć we wpisie niż kuking\.media\.max_per_post',
    'Regulamin poprawiony bez kopii w archiwum': r'resources/legal/archiwum/regulamin-\d{4}-\d\d-\d\d\.md różni się od resources/legal/regulamin\.md',
    'Nowa data regulaminu bez pliku w archiwum': r'Brak resources/legal/archiwum/regulamin-\d{4}-\d\d-\d\d\.md\. Zmieniła się data regulaminu',
    'Plik archiwum regulaminu z inną datą w nagłówku': r'Plik regulamin-\d{4}-\d\d-\d\d\.md ma w nagłówku inną datę niż w nazwie',
    'Polityka poprawiona bez kopii w archiwum': r'resources/legal/archiwum/polityka-prywatnosci-\d{4}-\d\d-\d\d\.md różni się od resources/legal/polityka-prywatnosci\.md',
    'Nowa data polityki bez pliku w archiwum': r'Brak resources/legal/archiwum/polityka-prywatnosci-\d{4}-\d\d-\d\d\.md\. Zmieniła się data polityki',
    'Plik archiwum polityki z inną datą w nagłówku': r'Plik polityka-prywatnosci-\d{4}-\d\d-\d\d\.md ma w nagłówku inną datę niż w nazwie',
    'Starsza wersja polityki bez strony o wydaniu na prośbę': r'contains "Polityka prywatności — wersja z \d+ \S+ \d{4}"',
    'Zmiana istotna bez okresu przejściowego': '@@ @@ -\'\\d{4}-\\d\\d-\\d\\d\' \\+\'\\d{4}-\\d\\d-\\d\\d\'|contains \\"Nowa wersja obowiązuje od \\d+ \\S+ \\d{4}\\. Do tego dnia|@@ @@ Array &0 \\[ - 0 => \'\\d{4}-\\d\\d-\\d\\d\', \\+ 0 => \'\\d{4}-\\d\\d-\\d\\d\'',
    'Zmiana istotna wchodzi w dniu publikacji zamiast po 14 dniach': r'Failed asserting that false is true\.|contains "Nowa wersja obowiązuje od \d+ \S+ \d{4}\.|\d{4}-\d\d-\d\d.*\d{4}-\d\d-\d\d|exception of type "RuntimeException" is thrown',
    'Zgoda zapisuje wersję opublikowaną zamiast obowiązującej': r"@@ @@ Array &0 \[ - 0 => '\d{4}-\d\d-\d\d', \+ 0 => '\d{4}-\d\d-\d\d', 1 => '\d{4}-\d\d-\d\d'",
    'Nagłówek polityki z inną datą niż dziennik zgód': r'Nagłówek polityki prywatności i `kuking\.zgody\.wersja_polityki` mówią',
    'IaC: plan produkcji bez filtra gałęzi docelowej': r'`pull_request` musi mieć `branches: \[main\]` — filtr gałęzi DOCELOWEJ',
    'IaC: plan produkcji bez base.ref == main': r'Job `plan` musi wymagać PR-a do main \(#',
    'Mediana wpisów bez warunku rodzaju': r'Failed asserting that 2\.5 is identical to 4\.0\.',
    'Mediana pytań liczy dopiski jako odpowiedź': r'Failed asserting that 1\.5 is identical to 1\.0\.',
    'Indeks pytań z predykatem na daniach': r'Licznik gościa nie trafia w indeks pytań\.',
    'Licznik widza bez poprawki na blokady': r"@@ @@ -'Czeka na odpowiedź \(1\)' \+'Czeka na odpowiedź \(2\)'",
    'Dopisek autora liczony jako odpowiedź': r'Failed asserting that 1 is identical to 0\.',
    'Odpowiedź nie odświeża licznika pytań': r'Failed asserting that 1 is identical to 0\.',
    'Odczyt kartki publikuje przepis': r'publikuje przepis\.',
    'Wspólny limit ignoruje nowe próby importu': r"is identical to 'dzien'|is identical to 'miesiac'",
    'Odczyt: rezerwacja bez śladu po awarii zapisu': r'Rezerwacja bez śladu w zleceniu została w budżecie — kolejne importy',
    'Odczyt: porzucona rezerwacja nie wygasa': r"@@ @@ Array &0 \[ - 'zarezerwowano' => 0, \+ 'zarezerwowano' => \d+",
    'Odczyt: rozliczenie bez strażnika stanu': r'Drugie rozliczenie tej samej próby musi być niczym\.',
    'Odczyt: zadanie za commitem zlecenia': r'Zlecenie `oczekuje` zostało zatwierdzone bez zadania w kolejce — nikt',
    'Odczyt: ponowienie woła model mimo zapisanej odpowiedzi': r'Failed asserting that actual size 2 matches expected size 1\.',
    # #2213: stary bezwarunkowy zapis `w_toku` na domkniętym zleceniu łamie
    # CHECK kodu błędu — objawem mutacji jest ten wyjątek, nie asercja.
    'Odczyt: bezwarunkowy zapis w_toku wskrzesza zlecenie': Wyjatek(r'QueryException.*importy_przepisow_kod_przy_bledzie_check'),
    'Wartości odżywcze liczone poniżej 90% pokrycia': r'Failed asserting that true is false\.|„Chleb pszenno-żytni na zakwasie”: Failed asserting that two strings',
    'Źródła wartości odżywczych bez identyfikatora wersji CIQUAL': r'Wersja CIQUAL ma być wskazana identyfikatorem, nie tylko nazwą\.',
    'Job plan IaC bez bramki produkcji': r'Job `plan` w \.github/workflows/railway-iac\.yml wykonuje',
    'unserialize ładunku kolejki bez allowed_classes': r'unserialize\( bez `allowed_classes` \(albo z `true`\) odtwarza KAŻDĄ',
    'Ślad listu odtwarza obcą klasę z failed_jobs': r'Klasa powiadomienia spoza `PolecenieZadania::WOLNO_ODTWORZYC`|Obca klasa z `failed_jobs` została odtworzona — `unserialize\(\)` bez|Failed asserting that an instance of class',
    'Planer bez filtra widoczności przepisu': 'does not contain "Sekretny bigos"|@@ @@ -\'Skopiowane z poprzedniego tygodnia: 2 pozycje\\. Pominięte: 1 pozycja |@@ @@ Array &0 \\[ - 0 => null, - 1 => true, \\+ 0 => \'Schowany sernik\', \\+ 1 => ',
    'Planer bez dziennego limitu pozycji': r'Session is missing expected key \[errors\]\.',
    'Wymazanie konta nie kasuje planu tygodnia': r"@@ @@ Array &0 \[ - 0 => 'Plan zostaje', \+ 0 => 'Plan do skasowania', \+ 1 => ",
    'Lista zakupów bez filtra widoczności przepisu': r'Not to contain: Sekretny bigos|does not contain "Sekretny bigos"',
    'Lista zakupów bez ostrzeżenia przy ponownym dodaniu przepisu': r"-'http://localhost:8000/przepisy/[^']+/lista-zakupow' \+'http://localhost:8000/lista-zakupow'",
    'Lista zakupów bez limitu pozycji': r'Session is missing expected key \[errors\]\.',
    'Lista zakupów: usunięcie pozycji bez Policy': r'Expected response status code \[403\] but received 302\.',
    'Lista zakupów: pojedyncze usunięcie bez pytania (#2466)': r'BRAK_POTWIERDZENIA_2466',
    'Wymazanie konta nie kasuje listy zakupów': r"-\s+0 => 'lista zostaje',\s+\+\s+0 => 'lista do skasowania',",
    'Zrobione w Planerze: policy wpuszcza cudzą osobę (#2593)': r'Expected response status code \[403\]',
    'Zrobione w Planerze: domena nie sprawdza własności (#2593)': r'Domena musi traktować cudzą pozycję jak nieistniejącą\.',
    'Zrobione w Planerze: kopia tygodnia przenosi oznaczenie (#2593)': r'Kopia nie przenosi historii realizacji\.',
    'Zrobione w Planerze: rollback nie odmawia przy oznaczeniach (#2593)': r'Rollback skasował oznaczenia ludzi bez pytania\.',
    'Dopisek w Planerze: policy wpuszcza cudzą osobę (#2549)': r'Expected response status code \[403\]',
    'Dopisek w Planerze: domena nie sprawdza własności (#2549)': r'Domena musi traktować cudzą pozycję jak nieistniejącą\.',
    'Dopisek w Planerze: stara karta nadpisuje nowszy dopisek (#2549)': r"-'konflikt'",
    'Dopisek w Planerze: kopia tygodnia gubi dopisek (#2549)': r'Kopia ma zachować dopisek\.',
    'Dopisek w Planerze: rollback nie odmawia przy dopiskach (#2549)': r'Rollback skasował dopiski ludzi bez pytania\.',
    'Dopisek w Planerze: polityka bez wiersza o dopisku (#2549)': r'nie opisuje dopisku przy przepisie w planie albo podaje inny limit',
    'Odłożenie szkicu: policy wpuszcza cudzą osobę (#2550)': r'Expected response status code \[403\]',
    'Odłożenie szkicu: domena nie sprawdza autorstwa (#2550)': r'Domena musi traktować cudzy szkic jak nieistniejący\.',
    'Odłożenie szkicu: bieżąca lista pokazuje też odłożone (#2550)': r'Failed asserting that .* does not contain "Pierogi odłożone"|Failed asserting that .* does not contain "Odłożony numer|Failed asserting that .* does not contain "Bieżący"|Failed asserting that .* does not contain "Szarlotka bieżąca"|Failed asserting that .* contains "Wszystkie Twoje szkice są odłożone|Failed asserting that .* contains "Nie masz teraz odłożonych szkiców"',
    'Odłożenie szkicu: publikacja nie zdejmuje oznaczenia (#2550)': Wyjatek(r'Check violation.*recipes_odlozony_tylko_niepublikowany_check'),
    'Odłożenie szkicu: rollback nie odmawia przy odłożonych (#2550)': r'Rollback skasował oznaczenia ludzi bez pytania\.',
    'Poprawka zakupów: rollback nie odmawia przy poprawionych pozycjach (#2443)': r'Rollback skasował informację o poprawkach bez pytania\.',
    'Poprawka zakupów: stara karta nadpisuje nowszą korektę (#2443)': r'Stara karta nie może nadpisać nowszej korekty\.',
    'Wydruk zeszytu znowu domyślnie z notatkami (#2438)': r'Domyślny wydruk zeszytu pokazał prywatną notatkę\.',
    'Rollback listy zakupów nie odmawia przy danych': r'Rollback skasował listy zakupów ludzi bez pytania\.',
    'Limit push nie liczy rezerwacji w transporcie': r'Drugi worker przekroczył limit 1\.',
    'Recover alarmu pomija potwierdzona odmowe': r'Failed asserting that true is false\.',
    'Preview wkleja ręczny pr_number w run:': r'Dane od użytkownika wklejone w treść `run:` — GitHub podstawia je',
    'IaC wkleja inputs.* w podsumowanie': r'Dane od użytkownika wklejone w treść `run:` — GitHub podstawia je',
    'DEPLOYMENT.md nazywa scheduler „cron”': r'Blok topologii w docs/DEPLOYMENT\.md znowu nazywa czwarty proces',
    'Obraz runtime bez poppler-utils': r'Etap `runtime` nie instaluje `poppler-utils` — import PDF na',
    'Cofnięcie importu bez odmowy przy niesprawdzonym szkicu': r'contains "Liczba: 1\."',
    'Szablon .env bez tokenu czyszczenia CDN': r'\.env\.example ma 0 wystąpień `CLOUDFLARE_PURGE_TOKEN` — oczekiwane',
    'README: „Dopóki ich nie ma” wraca': r'README mówi, że GitHub Actions nie działają, a ci\.yml mówi, że CI',
    'CHANGELOG z tym samym wpisem dwa razy': r'CHANGELOG\.md ma zdublowane wpisy — najczęściej skutek rozwiązania',
    'Archiwum CHANGELOG z tym samym wpisem dwa razy': r'CHANGELOG\.md ma zdublowane wpisy — najczęściej skutek rozwiązania',
    'CHANGELOG bez odnośnika do pliku archiwum': r'Pliki w docs/changelog/ bez odnośnika w CHANGELOG\.md',
    'Nowa funkcja bez akapitu na stronie Co nowego': r'CHANGELOG\.md ma w sekcji „## Nieopublikowane” \d+ wpis\(ów\) oznaczonych',
    'Dziennik wdrożeń: down() bez warunku odmowy': r'Cofnięcie przeszło, mimo że w dzienniku jest wiersz\.',
    'Co nowego bez dopisku „od numeru”': r'contains "od Alfa 0\.\d+\.\d+"|Strona „Co nowego” nie pokazuje „od Alfa 0\.\d+\.\d+” przy nagłówku',
    'Co nowego: brak nagłówka w fixture integracyjnej': r'contains "od Alfa 0\.\d+\.\d+"',
    'Cofnięcie no_amount bez odmowy przy oznaczonych składnikach': r'Cofnięcie przeszło i skasowało kolumnę `no_amount`\.',
    'Wycofanie Web Push bez odmowy przy wybranej ciszy nocnej': r'contains "D-088"',
    'Martwe odwołanie D-NNN w AGENTS.md': r'Odwołania do decyzji, których nie ma w dzienniku, albo identyfikatory',
    'Roboczy identyfikator w AGENTS.md': r'Odwołania do decyzji, których nie ma w dzienniku, albo identyfikatory',
    'Roboczy nagłówek w dzienniku decyzji': r'Nagłówki dziennika, które nie są ostatecznym, trzycyfrowym numerem|Odwołania do decyzji, których nie ma w dzienniku, albo identyfikatory',
    'Strażnik dziennika ślepy na dopisek ROBOCZA': r'Failed asserting that actual size 0 matches expected size 1\.|contains "D.1000.ROBOCZA"',
    'Strażnik dziennika ślepy na identyfikator czterocyfrowy': r'Failed asserting that actual size 0 matches expected size 1\.',
    'Runbook: railway config apply bez KUKING_WAIT_FOR_CI': r'`railway\.ts` odmawia bez KUKING_WAIT_FOR_CI \(#',
    'Workflow cen: checkout z kodem bez persist-credentials: false': r'Job „pobierz” uruchamia kod repozytorium i nie ma dostępu do',
    'Deploy: dane zdarzenia wklejone do Basha': r'Blok `run:` w deploy\.yml zawiera wyrażenie GitHuba — podstawiane do|Zła nazwa środowiska dla',
    'Strażnik migracji ślepy na FK dodany przez Blueprint': r'Strażnik nie zauważył FK dodanego przez Blueprint na istniejącej',
    'Strażnik migracji ślepy na indeks bez CONCURRENTLY': r'Strażnik nie zauważył indeksu bez CONCURRENTLY na istniejącej tabeli\.',
    'Strażnik migracji ślepy na CHECK/FK bez NOT VALID': r'Strażnik nie zauważył CHECK bez NOT VALID na istniejącej tabeli\.',
    'Job lint bez wspólnych kontroli powłoki': r'contains "run: bash scripts/kontrole-powloki\.sh"|ci\.yml \(job lint\) uruchamia test z tests/skrypty/ bezpośrednio\.',
    'Test powłoki wypada z listy wspólnego skryptu': r'tests/skrypty/bramka-migracji\.sh wypadł z listy\.|Test powłoki poza listą w scripts/kontrole-powloki\.sh — dopisz go do',
    # #1751 (D-332): forma zwracania się i nowa wersja polityki. Wzorce dopisane
    # w recenzji paczki H z komunikatów porażek po mutacji (lokalnie, PG 55439).
    'Cofnięcie formy zwracania się bez odmowy': r'Rollback przeszedł mimo zapisanego wyboru formy',
    'Anonimizacja zostawia formę zwracania się': r"Failed asserting that 'feminine' is null\.",
    'Helper formy ignoruje formę żeńską': (
        r"-'ugotowałaś' \+'gotujesz'"
        r'|contains "Możesz od razu pokazać, co dziś ugotowałaś"'
        r'|contains "Zacznij od zdjęcia tego, co dziś ugotowałaś\."'
        r'|matches PCRE pattern "~data-minutniki-koniec>Ugotowałam</a>~u"'
        r'|contains "Halina ugotowała Twój przepis'
        r'|contains "Kuking\.pl - pokaż, co dziś ugotowałaś\."'
        # #1753 etap 2: przycisk „Ugotowałam” na stronie przepisu i w formularzu.
        r'|matches PCRE pattern "~href="\[\^"\]\*/ugotowalem\[\^"\]\*">Ugotowałam</a>~u"'
        # #1753 etap 3: stopki listów do konta i o zmianie adresu — asercja
        # z komunikatem „Stopka listu <nazwa>” i samym „pokaż, co dziś …”.
        r'|^Stopka listu .* contains "pokaż, co dziś ugotowałaś\."'
    ),
    'Wariant neutralny helpera z rodzajem': r'wariant neutralny z rodzajem|contains "Możesz od razu pokazać, co dziś gotujesz"',
    'Goły rodzaj obok wywołania helpera': r'Tekst przypisuje czytelnikowi płeć:.*ugotowałaś',
    'Rollback paska polityki bez odmowy': r'Rollback przeszedł, choć ktoś zamknął pasek',
    # Decyzja właściciela z 29.09.2026 (wieczór): zmiana drobna od razu.
    'Polityka z terminem wejścia niezgodnym z konfiguracją': r'contains "obowiązuje od dnia publikacji"',
    'Pasek polityki przy drobnej zmianie': r'does not contain "data-pasek-zmiany-polityki"',
    'Wybór formy widoczny w okresie przejściowym polityki': r'does not contain "Jak mamy do Ciebie pisać\?"',
    'Wybór formy czeka na dzień wersji przy drobnej zmianie': r'Wybór formy ukryty w chwili 2026-09-29 20:00',
    # #2000: wspólny zeszyt „wszyscy” ma „Podziel się”.
    'Wspólny publiczny zeszyt bez „Podziel się”': r'Wspólny zeszyt „wszyscy” nie ma przycisku „Podziel się”',
    # #2224: stary KRS w dokumencie ma wywrócić strażnika danych rejestrowych.
    'Audyt ADR: stary KRS operatora': r'Numer rejestrowy w dokumencie różni się od config/kuking\.php.*0000854321',
    # #2223 (D-333): tinker poza obrazem produkcyjnym.
    'Tinker wraca do require': r'laravel/tinker wrócił do `require`',
    'Runbook znów każe użyć tinkera': r'MONITORING_BLEDOW\.md każe użyć `php artisan tinker`',
    # #599: poczta jako drugi kanał alarmowy (wzorce zebrane przy scalaniu paczki K,
    # ręcznie na bazie stanowiska — gałąź #599 dodała wpisy bez wzorców).
    'List alarmowy bez znacznika rezerwacji': r"Znacznik ListZarezerwowany ma klasa spoza rejestru.*'app/Mail/AlarmOperacyjny\.php'",
    'Poczta wypada z kanałów alarmowych': r'\[App\\Mail\\AlarmOperacyjny\] mailable was not sent|The total number of mailables sent was 0 instead of [12]\.|KanalAlarmowyMailemTest\.php:161|- \'blad_email\' => false|Output does not contain "poczta \(KUKING_ALARM_EMAIL\) PRZYJĄŁ"|Expected status code [01] but received [01]\.',
    'Awaria poczty przewraca raport i zabiera Discord': Wyjatek(r'TransportException: niedostępny'),
    'List alarmowy bez dobowego sufitu': r'The total number of mailables sent was 3 instead of 2\.',
    'List alarmowy niesie komunikat wyjątku': r'does not contain "ktos@example\.com"|\[App\\Mail\\AlarmOperacyjny\] mailable was not sent',
    # Audyt infra 30.09.2026 (#2293, #2296, #2298, #2301, #2302).
    'Kolejka traci proc_open (#2293)': r'równa liście z docker/php\.ini minus proc_open|Proces kolejki z produkcyjnym php\.ini nie ma proc_open',
    'queue:work bez listy funkcji kolejki (#2293)': r'queue:work nie dostaje listy funkcji bez proc_open',
    'Job PR-a bez straży forka (#2298)': r'może trafić z forka na własny runner',
    'Bramka deployu bez warunku repozytorium (#2298)': r'bez warunku head_repository\.full_name == github\.repository',
    'Nagłówek deploy.yml znów o repo prywatnym (#2302)': r'mówi, że repozytorium jest prywatne albo ma pulę 2 000 minut',
    'Runbook #595 bez wyłącznika życzeń (#2296)': r'runbook .* ich nie wymienia.*KUKING_URODZINY_MAIL_WLACZONY',
    'Composer bez config.platform.php (#2301)': r'config\.platform\.php = 8\.4\.0 odtwarza błąd #2301|wymagają nowszego PHP niż config\.platform\.php 8\.4\.0',
    'Nowa migracja w starej grupie znacznika (#2302)': r'Migracja ze znacznikiem czasu, który ma już inna migracja',
    # #2309, #2310, #2263, #2233, #2230, #2248: łańcuch dostaw CI i bramka wdrożenia.
    'Krok CI dodaje klucz PGDG z pominięciem odcisku': r'sam dodaje repozytorium PGDG albo instaluje klienta PostgreSQL z APT',
    'Klient PostgreSQL 18 bez sprawdzenia odcisku klucza PGDG': r'Skrypt klienta nie sprawdza odcisku pobranego klucza PGDG|Test skryptu klienta PostgreSQL 18 oblał: Klient PostgreSQL 18: \d+ oblanych przypadków',
    'openpyxl bez --require-hashes': r'instaluje pakiety Pythona bez --require-hashes',
    'Zależność openpyxl bez hasha w pliku wymagań': r'wymaganie „et-xmlfile==2\.0\.0” nie ma dokładnej wersji \(==\) i hasha',
    'Usługa PostgreSQL w CI z ruchomego tagu': r'obraz `postgres:18-alpine` bez digestu — tag jest ruchomy',
    'Digest usługi PostgreSQL inny niż w Dockerfile Dependabota': r'ma inny digest niż FROM w docker/ci-postgres/Dockerfile',
    'Bramka Railway checkoutuje bieżący main zamiast SHA z CI': r'Checkout bramki nie ma `ref: \$\{\{ github\.event\.workflow_run\.head_sha \}\}`',
    'Skrypt bramki Railway nie porównuje HEAD z SHA z CI': r'Skrypt bramki nie porównuje `git rev-parse HEAD` z SHA z CI',
    'Bramka Railway wdraża po CI bez sukcesu (#2025)': r"musi mieć warunek `github\.event\.workflow_run\.conclusion == 'success'`",
    'Job zbiorczy CI zmienia nazwę, bramka go nie znajdzie (#2025)': r'Job zbiorczy w ci\.yml nie nazywa się już',
    'Alarm audit_ci bez odczytu przebiegów (#2025)': r'Bez `actions: read` alarm nie odczyta przebiegów CI',
    'Wydanie Sentry z github.sha zamiast SHA wdrożenia': r'Wydanie Sentry ma version: \$\{\{ github\.sha \}\}, a powinno',
    'Nieznany stan w historii wdrożenia pominięty': r'OBLANE: nieznany stan w historii = błąd wejścia \(#2248\) \(kod 0, oczekiwano 2\)',
    # Audyt prywatności 30.09 (#2278, #2281, #2282).
    'Polityka bez nazwy ciasteczka zapamiętaj mnie': r'Polityka nie podaje nazwy ciasteczka „zapamiętaj mnie”',
    'Polityka z terminem zapamiętaj mnie innym niż bramka': r'Ciasteczko „zapamiętaj mnie” żyje 400 dni',
    'Klucz localStorage bez opisu w polityce': r'zapisuje w localStorage „kuking-wyglad-nowy”',
    'Planer bez wiersza w polityce': r'Dane z sekcji paczki „planer” nie mają opisu',
    'Nowa sekcja paczki bez opisu w polityce': r'Paczka ma nową sekcję „planer_nowy”',
    'Polityka bez górnego terminu usunięcia wspólnego gotowania (#2708)': r'Polityka nie podaje górnego terminu usunięcia \(48 godzin\) w wierszu „Wspólne gotowanie”',
    'Wspólne gotowanie nie jest kasowane na granicy terminu (#2708)': r'RETENCJA_2708_SESJA_NIEUSUNIETA_NA_GRANICY',
    'Postęp gotowania z terminem niezgodnym z konfiguracją': r'Postęp gotowania żyje 24 godzin',
    'Cloudflare jako pośrednik bez wiersza w polityce': r'Kod używa usługi „Cloudflare \(sieć, CDN i ochrona',
    # #2267: theme-color i manifest.
    'Pasek przeglądarki znów zawsze ciemny': r'Jasna strona bez wyboru ma jasny pasek przeglądarki',
    'Manifest wraca do ciemnego theme_color': r'Manifest ma kolor jasnego motywu',
    # UX-02 (#2287).
    'Pusty dzień planera znów w 16 px': r'stoi samo, a ma 16 px zamiast tekstu podstawowego',
    'Samodzielne zdanie pomocnicze w arkuszu na 16 px': r'Samodzielne zdanie pomocnicze nie ma rozmiaru tekstu podstawowego',
    # D-333: obie gałęzie strażnika mówią to samo zdanie (ekran i szablon).
    'Logowanie bez novalidate': r'Formularze? z natywną walidacją bez `novalidate` \(D-333\).*auth/login|Formularze? z natywną walidacją bez `novalidate` \(D-333\).*/login \(gość\)',
    'Wybór zeszytu bez novalidate': r'Formularz z natywną walidacją bez `novalidate` \(D-333\).*components/wybor-zeszytu\.blade\.php',
    # #2308: kursor z adresu tylko przez KursorListy.
    'Strona tagu stronicuje gołym cursorPaginate': r'Lista kursorowa bez KursorListy — zmyślony `\?cursor=` da tam HTTP 500 \(#2308\)\. Użyj `KursorListy::strona\(\)`',
    # Audyt prywatności 30.09, Z8–Z11 (#2283).
    'Retencja failed_jobs inna niż w polityce': r'żyje 7 dni — tyle, ile queue:prune-failed w harmonogramie',
    'Polityka znów obiecuje e-mail o zmianie': r'Polityka §9 obiecuje e-mail o zmianie polityki',
    'Polityka pomija zdjęcie z zakresu Google': r'a polityka nie mówi, że Google pyta o zdjęcie profilowe',
    'Regulamin §2 bez „Poradźcie”': r'Serwis ma /pytania, a regulamin §2 nie wymienia tej usługi',
    # #2299: zawężenie `--filter` w kontrolach ma własne regresje w każdej części.
    'Kontrole bez regresji zawężenia filtra (#2299)': r'Części kontroli nie uruchamiają `scripts/test_zawezenie_testow\.py` \(#2299\)',
    'Macierz panelu krótsza niż podział (#2299)': r'Macierz `port_panelu` w ci\.yml ma inne części niż `CZESCI_PANELU`',
    'Panel marki bez numeru części (#2299)': r'Job `port_panelu` nie podaje `PANEL_CZESC` z macierzy',
    'Build obrazu biegnie na drafcie (D-333, 2.10.2026)': r'draft PR: biegną .*docker-build',
    'Kontrole negatywne na drafcie (D-333, 2.10.2026)': r'draft PR: części kontroli negatywnych w macierzy: \[1\]',
    'Agregat panelu zielony bez części na pełnym przebiegu (D-333, 2.10.2026)': r'`panel_marki` przy części=skipped, pelny=true: kod wyjścia 0, ma być 1',
    'Bramka skraca także push z DRAFT=true (D-333, 2.10.2026)': r'push \(z DRAFT=true w środowisku\): bramka wystawiła pelny=false',
    'Job zbiorczy panelu pomijany po czerwonej części (#2299)': r'Job zbiorczy panelu bez `!cancelled\(\)` jest `skipped` po czerwonej części',
    'Testy JS nie biegną nigdzie, bo assets też buduje sam Vite (#2299)': r'Job `assets` nie robi pełnego `npm run build`',
    'Cache przeglądarki odtwarza inną wersję (#2299)': r'przeglądarka innej wersji nie może być odtwarzana \(#2299\)',
    'Pomiar portu zależny od rodzaju runnera (#2299)': r'warunek runnera stoi na kroku innym niż cache przeglądarki',
    'Cache przeglądarki na własnym runnerze (#2299)': r'cache przeglądarki na własnym runnerze podmieniałby wspólny katalog',
    # #2405 i #2406: dostępność formy zwracania się i kroków onboardingu.
    'Błąd wyboru formy bez stabilnego id (#2405)': r'Komunikat błędu wyboru formy musi mieć jeden stabilny id',
    'Radia formy nie wskazują błędu w aria-describedby (#2405)': r'Radio nie wskazuje komunikatu błędu przez aria-describedby',
    'Radia formy bez aria-invalid (#2405)': r'Radio nie ma aria-invalid="true"',
    'Onboarding bez aria-current na bieżącym kroku (#2406)': r'elementów z aria-current="step", powinien być jeden',
    'Onboarding bez grupy z nazwą kroków (#2406)': r'nie ma grupy kroków z role="group"',
    'Odwołanie od blokady CSAM bez ochrony decyzji (#2427)': r'CSAM_BAN_APPEAL_MUST_STAY_OPEN',
    'Zabezpieczony awatar znów ma wariant do pokazania (#2708)': r'CSAM_AWATAR_2708_NIE_WYCIEKA',
    'Runbook odtworzenia stosuje rejestr usunięć po podpięciu bazy (#2708)': r'RUNBOOK_REJESTR_PO_PODPIECIU',
    'Runbook podpina bazę przed drugim wymazaniem (#2708)': r'RUNBOOK_DRUGI_WYMAZ_PRZED_PODPIECIEM',
    'Awaria izolacji usług pozwala wymazać przed sprawdzeniem CSAM (#2708)': r'CSAM_AWARIA_NIE_POMIJA_SPRAWDZENIA',
    'Odtworzenie CSAM po pierwszym wymazaniu kont (#2708)': r'CSAM_PRZED_PIERWSZYM_WYMAZANIEM',
    'Odtworzenie nowych decyzji CSAM po ponownym wymazaniu (#2708)': r'CSAM_PRZED_PONOWNYM_WYMAZANIEM',
    'Zepsute kodowanie polskich liter w komunikacie Planera (paczka L)': r'Polskie litery zapisane w zepsutym kodowaniu.*PlanerController\.php',
    'Ścisłe gotowanie przyjmuje ukrytą wersję (#2808)': r'GOTUJ_2808_UKRYTA_WERSJA',
}


def kontrole_mechanizmu(plik, test, mutacja_z_asercja, replace_once):
    """Kontrole dodatnie SAMEGO MECHANIZMU: czerwień z niewłaściwego powodu ma nie zaliczać.

    Dwie mutacje na tym samym strażniku; przebieg wymaga werdyktu ZLA_PRZYCZYNA
    (gdyby dostały POTWIERDZONA, cały krok pada — mechanizm sam jest zepsuty):

      1. Fatal zamiast asercji: średnik zdjęty z zamknięcia instrukcji, PHP nie
         załaduje klasy (ParseError). Wzorzec `.` pasuje do wszystkiego, więc
         odrzucić go może tylko rozpoznanie wyjątku albo brak raportu — dokładnie
         to, co mechanizm przestałby umieć, gdyby wrócił do liczenia samego
         słowa `FAILED`.
      2. Właściwa asercja, obcy komunikat: ta sama mutacja co w kontroli
         strażnika, ale ze wzorcem, którego test nigdy nie wypisze. Dowód, że
         wzorzec jest naprawdę porównywany z prawdziwym wyjściem PHPUnita.
    """
    return [
        ("Mechanizm: fatal zamiast asercji", plik, test,
         lambda s: replace_once(s, "return 'ścieżka spoza API dostawcy';", "return 'ścieżka spoza API dostawcy'"),
         "."),
        ("Mechanizm: asercja z obcym komunikatem", plik, test,
         mutacja_z_asercja,
         "Komunikat, którego ten test nigdy nie wypisze"),
    ]
