import { chromium } from 'playwright';
import { execFileSync, spawn } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';

mkdirSync('audit-evidence/browser', {recursive:true});
const base = 'http://127.0.0.1:8123';
const server = spawn('php', ['artisan','serve','--host=127.0.0.1','--port=8123'], {stdio:'ignore'});
const results = [];
const db = (code) => execFileSync('php',['artisan','tinker','--execute',code],{encoding:'utf8'}).trim();
let browser;
try {
  for (let i=0;i<60;i++) {try {if((await fetch(base+'/health')).ok)break;}catch{} await new Promise(r=>setTimeout(r,250));}
  browser = await chromium.launch({headless:true});
  const ctx = await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844},reducedMotion:'reduce'});
  const page = await ctx.newPage();
  page.setDefaultTimeout(12000);
  const snap = async (name) => {
    await page.screenshot({path:`audit-evidence/browser/${name}.png`,fullPage:true});
    const html=await page.content();writeFileSync(`audit-evidence/browser/${name}.html`,html);
    results.push({step:name,url:page.url(),has_h1:await page.locator('h1').count(),body: (await page.locator('body').innerText()).slice(0,1800)});
  };
  await page.goto(base+'/register');
  await page.locator('[name=display_name]').fill('Audyt kuchni');
  await page.locator('[name=username]').fill('audyt_nowy');
  await page.locator('[name=email]').fill('audyt_nowy@example.test');
  await page.locator('[name=password]').fill('AuditKuchniaLosowe8673_!');
  await page.locator('[name=age_confirmed]').check();
  await page.locator('[name=terms_accepted]').check();
  await Promise.all([page.waitForNavigation(),page.locator('button[type=submit]').filter({hasText:'Załóż konto'}).click()]);
  await snap('01-registration');
  if(!page.url().includes('/witaj/')) throw Error('Registration did not finish');
  const skip=page.getByRole('link',{name:'Pomiń ten krok'});
  if(await skip.count()) await Promise.all([page.waitForNavigation(),skip.click()]);
  else await Promise.all([page.waitForNavigation(),page.getByRole('link',{name:'Dalej',exact:true}).click()]);
  await snap('02-people');
  await Promise.all([page.waitForNavigation(),page.getByRole('link',{name:'Pomiń ten krok'}).click()]);
  await snap('03-onboarding-done');
  await page.goto(base+'/home'); await snap('04-first-home');
  await page.goto(base+'/dodaj/zdjecie');
  await page.locator('[name=body]').fill('AUDYT pierwsze zdjecie bez JavaScriptu');
  await page.locator('input[type=file]').first().setInputFiles('audit-evidence/probe.png');
  await Promise.all([page.waitForNavigation(),page.getByRole('button',{name:'Opublikuj',exact:true}).click()]);
  await snap('05-first-photo');
  results.push({step:'photo-db',value:db("echo App\\Models\\Post::where('body','AUDYT pierwsze zdjecie bez JavaScriptu')->count();")});
  await page.goto(base+'/dodaj/przepis'); await snap('06-nojs-wizard');
  const fallback=page.locator('noscript a');
  if(await fallback.count()) await Promise.all([page.waitForNavigation(),fallback.first().click()]);
  else await page.goto(base+'/dodaj/przepis/jedna-strona');
  await page.locator('[name=title]').fill('AUDYT zupa bez JavaScriptu');
  await page.locator('[name="ingredients[0][text]"]').fill('marchew');
  await page.locator('[name="steps[0][instruction]"]').fill('Ugotuj marchew w wodzie.');
  await page.locator('[name=source_type][value=own]').check();
  await page.locator('[name=visibility][value=public]').check();
  await Promise.all([page.waitForNavigation(),page.locator('button[name=action][value=publish]').click()]);
  await snap('07-first-recipe');
  results.push({step:'recipe-db',value:db("echo App\\Models\\Recipe::where('title','AUDYT zupa bez JavaScriptu')->where('status','published')->count();")});
  const other=db("echo App\\Models\\Recipe::whereHas('author.profile',fn($q)=>$q->where('username','<>','audyt_nowy'))->where('status','published')->value('slug');");
  await page.goto(base+'/przepisy/'+other+'/ugotowalem');
  await page.locator('[name=note]').fill('AUDYT ugotowalem bez JavaScriptu');
  await Promise.all([page.waitForNavigation(),page.getByRole('button',{name:'Wyślij',exact:true}).click()]);
  await snap('08-cooked');
  results.push({step:'cooked-db',value:db("$e=App\\Models\\CookedEvent::where('note','AUDYT ugotowalem bez JavaScriptu')->first(); echo json_encode(['event'=>(bool)$e,'notifications'=>$e?App\\Models\\Notification::where('data->cooked_event_id',$e->id)->count():0]);")});
  const form=page.locator('form').filter({has:page.locator('button').filter({hasText:'Wyślij komentarz'})}).last();
  await form.locator('[name=body]').fill('AUDYT komentarz bez JavaScriptu');
  await Promise.all([page.waitForNavigation(),form.locator('button[type=submit]').click()]);
  await snap('09-comment');
  results.push({step:'comment-db',value:db("echo App\\Models\\Comment::where('body','AUDYT komentarz bez JavaScriptu')->count();")});
  const ctxJs=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce',storageState:await ctx.storageState()});
  const p=await ctxJs.newPage();await p.goto(base+'/home');
  const dimensions=()=>p.evaluate(()=>({body:parseFloat(getComputedStyle(document.body).fontSize),html_scale:document.documentElement.dataset.textScale,paragraphs:[...document.querySelectorAll('main p')].filter(e=>e.getBoundingClientRect().height).slice(0,12).map(e=>({text:e.textContent.trim().slice(0,90),size:getComputedStyle(e).fontSize})),buttons:[...document.querySelectorAll('main .btn')].filter(e=>e.getBoundingClientRect().height).map(e=>({text:e.textContent.trim().slice(0,50),height:e.getBoundingClientRect().height,width:e.getBoundingClientRect().width})),overflow:document.documentElement.scrollWidth>innerWidth,css:[...document.styleSheets].map(s=>s.href)}));
  const normal=await dimensions();
  await p.goto(base+'/ustawienia/czytelnosc');await p.locator('[name=text_scale][value="1.4"]').check();
  await Promise.all([p.waitForNavigation(),p.getByRole('button',{name:'Zapisz',exact:true}).click()]);
  await p.goto(base+'/home');const large=await dimensions();
  await p.screenshot({path:'audit-evidence/browser/10-text-scale-140.png',fullPage:true});
  results.push({step:'built-css-scale',normal,large});
  await p.setViewportSize({width:320,height:844});await p.reload();results.push({step:'built-css-320',...(await dimensions())});
  await p.screenshot({path:'audit-evidence/browser/11-width-320.png',fullPage:true});
} catch(e) {results.push({error:String(e),stack:e.stack});process.exitCode=1;}
finally {writeFileSync('audit-evidence/browser/results.json',JSON.stringify(results,null,2));if(browser)await browser.close();server.kill();}
